# Generated by Django 3.1.1 on 2020-09-27 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('slug', models.CharField(max_length=256)),
                ('size', models.IntegerField(default=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'video categorie',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('article_link', models.CharField(blank=True, max_length=2048, null=True)),
                ('url_youtube_video', models.CharField(blank=True, max_length=2048, null=True)),
                ('url_youtube_thumb', models.CharField(blank=True, max_length=2048, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('url_feed_video', models.CharField(blank=True, max_length=2048, null=True)),
                ('url_feed_thumb', models.CharField(blank=True, max_length=2048, null=True)),
                ('video_file_type', models.CharField(default='video/mp4', max_length=32)),
                ('video_duration', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IDEIA', 'Idéia'), ('PRODUCAO', 'Produção'), ('REVISAO', 'Revisão'), ('APROVADO', 'Aprovado')], default='IDEIA', max_length=16)),
                ('categories', models.ManyToManyField(to='terra.VideoCategory')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='terra.feed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
