# Generated by Django 3.1.1 on 2020-09-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='thumbnail_uri',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='video_uri',
            field=models.CharField(default='http', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(blank=True, to='terra.VideoCategory'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('IDEIA', 'Idéia'), ('PRODUCAO', 'Produção'), ('REVISAO', 'Revisão'), ('APROVADO', 'Aprovado'), ('VIDEO_INVALIDO', 'Vídeo Inválido')], default='IDEIA', max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
