# Generated by Django 3.1.1 on 2020-10-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0002_auto_20200928_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
