# Generated by Django 3.1.1 on 2020-10-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0003_video_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_base_uri',
            field=models.CharField(default='https://SERVER_NAME/terra/FEED_SLUG/feed/video/', max_length=256),
            preserve_default=False,
        ),
    ]
