# Generated by Django 3.1.1 on 2020-10-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0005_auto_20201021_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='feed_base_uri',
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
