# Generated by Django 3.1.1 on 2020-12-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0006_auto_20201021_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['published']},
        ),
    ]
